### github-action-variable-04.yml

name: Test Github Actions variable-04
on: 
  workflow_dispatch

env:
  DAY_ON_WEEK: Friday
  
jobs:
  check-var:
    runs-on: ubuntu-latest
    env:
      MESSAGE: Hello
    steps:
      - name: "It's Day"
        if: ${{ env.DAY_ON_WEEK == 'Monday'}} 
        run: echo "$MESSAGE, Today is $DAY_ON_WEEK!"

  check-var2:
    runs-on: ubuntu-latest
    steps:
      - name: "It's Day"
        run: echo "$MESSAGE, Today is $DAY_ON_WEEK!"
        
  check-var3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruits: [apple, banana, kiwi]
    steps:
      - name: "It's fruits"
        run: echo "Hello,${{ matrix.fruits }}"
