### github-action-variable-01.yml

name: Test Github Actions variable-01
on: 
  push

env:
  DAY_ON_WEEK: Friday
  
jobs:
  check-var:
    runs-on: ubuntu-latest
    env:
      MESSAGE: Hello
    steps:
      - name: "It's Day"
        run: echo "$MESSAGE, Today is $DAY_ON_WEEK!"
